apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websocketchatwithsentiment
spec:
  paused: true
  replicas: {{ .Values.chat_replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: websocketchat
        lang: golang
    spec:
      containers:
      - name: chatws
        image: {{ .Values.chat_image }}:{{ .Values.chat_image_version }} 
        imagePullPolicy: Always
        env:
        - name: COGSURL
          value: {{ .Values.sentimentapi_uri}} 
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"